---
title: "Week1 Project Data Story"
author: Haozhong Zheng (hz2694)
runtime: shiny
output:
  html_document: default
  html_notebook: default
---

# Step 0 - Install and load libraries
```{r, message=FALSE, warning=FALSE}
packages.used=c("tm", "wordcloud", "RColorBrewer", "dplyr", "tidytext")

# check packages that need to be installed.
packages.needed=setdiff(packages.used, 
                        intersect(installed.packages()[,1], 
                        packages.used))
# install additional packages
if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE,
                   repos='http://cran.us.r-project.org')
}

library(tm)
library(wordcloud)
library(RColorBrewer)
library(dplyr)
library(tidytext)
library(knitr)
```

This notebook was prepared with the following environmental settings.

```{r}
print(R.version)
```

# Step 1 - Preparing Data
```{r, message=FALSE, warning=FALSE}
philosophy <- read.csv("../data/philosophy_data.csv", stringsAsFactors = FALSE)
```